# Challenges 1.0.0-SNAPSHOT-LOCAL Configuration
# This config file is dynamic and saved when the server is shutdown.
# You cannot edit it while the server is running because changes will
# be lost! Use in-game settings GUI or edit when server is offline.
#
commands:
  #
  # This enables/disables common command that will be independent from
  # all GameModes. For admins it will open selection with all GameModes
  # (unless there is one), but for users it will open GUI that corresponds
  # to their world (unless it is specified other way in Admin GUI).
  # This means that writing `/[user_global]` will open Challenges GUI's
  # and `/[admin_global]` will open Admin GUI's
  # /!\ In order to apply the changes made to this option, you must restart your server. Reloading BentoBox or the server won't work.
  global-command: false
  #
  # This allows to define which GUI will be opened when `single-gui` is enabled.
  # This option is ignored if `single-gui` is disabled.
  # Acceptable values:
  #    - CURRENT_WORLD - will open GUI that corresponds to user location.
  #    - GAMEMODE_LIST - will open GUI with all installed game modes.
  global-view-mode: GAMEMODE_LIST
  player:
    #
    # Allows to define a global challenges user command. This command will work
    # only if `global-commands` is enabled. This allows to execute `/challenges`
    # without referring to the gamemode.
    # /!\ In order to apply the changes made to this option, you must restart your server. Reloading BentoBox or the server won't work.
    global: challenges c
    #
    # Allows to define user command for opening challenges GUI's.
    # Unlike `global` command, this requires to have gamemode player command before it.
    # This will look like: `/[player_cmd] challenges`
    # /!\ In order to apply the changes made to this option, you must restart your server. Reloading BentoBox or the server won't work.
    main: challenges
    #
    # Allows to define complete command.
    # This will look like: `/[player_cmd] challenges complete`
    # /!\ In order to apply the changes made to this option, you must restart your server. Reloading BentoBox or the server won't work.
    complete: complete
  admin:
    #
    # Allows to define a global challenges admin command. This command will work
    # only if `global-commands` is enabled. This allows to execute `/chadmin`
    # without referring to the gamemode.
    # Note, this must not be the same as user global command.
    # /!\ In order to apply the changes made to this option, you must restart your server. Reloading BentoBox or the server won't work.
    global: challengesadmin chadmin
    #
    # Allows to define admin command for opening challenges GUI's.
    # Unlike `global` command, this requires to have gamemode admin command before it.
    # This will look like: `/[admin_cmd] challenges`
    # /!\ In order to apply the changes made to this option, you must restart your server. Reloading BentoBox or the server won't work.
    main: challenges
history:
  #
  # This indicate if player challenges data history will be stored or not.
  store-history-data: false
  #
  # This allows to specify an amount of time in days when history data will
  # be removed. 0 means that data will not be removed.
  lifespan: 14
gui-settings:
  #
  # Remove non-repeatable challenges from the challenge GUI when complete.
  remove-complete-one-time-challenges: false
  #
  # Add enchanted glow to completed challenges
  add-completed-glow: true
  #
  # This variable allows to choose which Challenges users can see in Challenges GUI.
  # Valid values are:
  #     'VISIBLE' - there will be no hidden challenges. All challenges will be viewable in GUI.
  #     'HIDDEN' - shows only deployed challenges.
  #     'TOGGLEABLE' - there will be button in GUI that allows users to switch from ALL modes.
  # TOGGLEABLE - Currently not implemented.
  undeployed-view-mode: VISIBLE
  #
  # This allows to change default locked level icon. This option may be
  # overwritten by each challenge level. If challenge level has specified
  # their locked level icon, then it will be used, instead of this one.
  locked-level-icon:
    ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: BARRIER
#
# This indicate if challenges data will be stored per island (true) or per player (false).
store-island-data: true
#
# Reset Challenges - if this is true, player's challenges will reset when users
# reset an island or if users are kicked or leave a team. Prevents exploiting the
# challenges by doing them repeatedly.
reset-challenges: true
#
# Broadcast 1st time challenge completion messages to all players.
# Change to false if the spam becomes too much.
broadcast-messages: true
title:
  #
  # Shows a title screen for player after completion a challenge or level.
  # Message can be edited via language settings.
  show-title: true
  #
  # Integer that represents how long title will be visible for player.
  title-showtime: 70
#
# Long that represents how frequently (in minutes) challenges addon will save data to database.
# If this is set to 0, saving will not happen.
auto-saver: 30
#
# This list stores GameModes in which Challenges addon should not work.
# To disable addon it is necessary to write its name in new line that starts with -. Example:
# disabled-gamemodes:
#  - BSkyBlock
disabled-gamemodes: []
configVersion: v3
